export const ActionTypes = {
    GET_USERS        : "GET USERS",
    GET_USER         : "GET USER",
    SUGGESTED_USER   : "SUGGESTED USER",
    SHOW_USER        : "SHOW USER",
    ACCEPT_USER      : "ACCEPT USER",
    GET_FRIENDS      : "GET FRIENDS",
    ADD_USER         : "ADD USER",
    SHOW_REQUESTS    : "SHOW REQUESTS",
    GET_POST         : "GET POST",
    GET_ALL_POSTS    : "GET ALL POSTS",
    ADD_COMMENT      : "ADD COMMENT",
    CREATE_POST      : "CREATE POST",
    LIKE_POST        : "LIKE POST",
    DISLIKE_POST     : "DISLIKE POST" ,
    GET_FLAGGED_POSTS: "FLAGGED POST",  
}